### ISSUE TITLE
Add Github Workflow is README.md

### ISSUE THREAD

**Issue by pranavvp16** [tfugnashik/examples#1]
As this repository aims for beginners to make contributions to open-source. Most of the people won't be familiar with the Github workflow. Writing a set of commands that can help anyone to contribute in the repository in  README.md or CONTRIBUTING.md can be helpful.
The commands should go like 
fork - > clone - > Code - > add -> commit -> push -> Make a PR

**Comment by deoraja** [comment]
can u please assign this to me @pranavvp16 
to begin - my approach would be -
1) fork 
2) git init (in git bash )
3)git clone copied link 
4) git checkout -b filename
5) git add filename

**Comment by pranavvp16** [comment]
Hello you don't need to git init while git clone and also we don't want to create branch so you can skip that part to

**Comment by deoraja** [comment]
Thank you so much for the oppurtunity and rectifying my approach
