### ISSUE TITLE
Graduate Admission Prediction Model

### ISSUE THREAD

**Issue by HrutikaBadgeri** [tfugnashik/examples#13]
I would like to work on a regression-based prediction problem set that allows us to predict the admission chances of students based on various factors like test scores etc. I want to explore different data visualization techniques and train the model using several regression-based ML models like SVR, DecisionTressRegressor, etc. 

Can you assign me this under hacktoberfest? :)

Dataset link: https://www.kaggle.com/datasets/hrutikabadgeri/graduate-admission-predict/data

**Comment by pranavvp16** [comment]
Yes please can work on this example. I will assign this to you

**Comment by HrutikaBadgeri** [comment]
Hey, is it okay if I also include the CSV file within the project folder?

**Comment by pranavvp16** [comment]
No please use the requests library to download the dataset from github, drive or any source you want. You can have a look at `Titanic_dataset` example or the `Movie_recommendation` example both use the requests library to fetch the dataset

**Comment by HrutikaBadgeri** [comment]
Okay sure
